name: CI
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Specs

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build and test with rspec
        env:
          RAILS_ENV: test
        run: bundle exec rspec spec
